# mysql 的数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver