server:
  port: 8081
  context-path: /JSHibernate # 访问地址：http://localhost:8081/
#  tomcat:
#    uri-encoding: UTF-8
#  session:
#    timeout:

  # spring mvc 视图解析器
  mvc:
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp

#  jpa:
#    hibernate:
#      ddl-auto: update # create (自动创建表,要先创建类,每次都是先删再创建) update：如果表存在则不创建，只在第一次初始化时创建表
#    show-sql: true